"""Test periodic-pattern induction (generalized FizzBuzz).

A sequence of ``n`` overlapping periodic "harmonics": the k-th fires at every
multiple of its period, and each position's label is the sep-joined
concatenation of every label whose period divides it
(:func:`generate_sequence`), over one full period, positions 1..lcm(periods).
Queries ask whether a label appears at a position
(:func:`tof_membership_query_gen`) or how many positions contain it
(:func:`numeric_count_query_gen`). Information conditions are declared in
exactly one place, the ``CONDITIONS`` mapping below, and rendered together in
one loop by :func:`get_periodic_prompts`; see ``CONDITIONS`` for what each
arm shows and why the ``zero`` arm needs a range-free question.

Every generator takes an explicit ``seed`` and builds a fresh
``np.random.default_rng(seed)``, never global RNG state. Generation is
byte-pinned by ``tests/induction/test_golden_quizzes.py`` at the notebooks'
production configs: any change to RNG call order/count, or to the
noise-padding scheme, breaks that pin -- fix the change, never re-baseline
the fixture.
"""

import string
from dataclasses import dataclass
from math import gcd, lcm
from types import MappingProxyType
from typing import Callable, Collection, Dict, Iterable, Mapping, Optional, Tuple, TypeAlias

import numpy as np

from smolbench.evals import Quiz, ToF, Numeric
from smolbench.evals.tokenization import (
    TiktokenTokenizer,
    Tokenizer,
    choose_whitespace_unit,
    token_matched_noise_prompt,
)
from smolbench.induction._common import (
    Prompter,
    RenderedQuery,
    build_substitution,
    context_renderer,
    quizzes_from_prompts,
    random_labels,
)

# Prompter is re-exported for callers configuring the benchmark; the class
# itself lives in ``_common`` with the rest of the generation machinery.
__all__ = [
    "PeriodicConfig",
    "Prompter",
    "Contexts",
    "Condition",
    "CONDITIONS",
    "RANGE_KEYS",
    "generate_sequence",
    "get_periodic_prompts",
    "get_periodic_quiz",
    "get_periodic_numeric_quiz",
    "tof_membership_query_gen",
    "numeric_count_query_gen",
]


# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

Label: TypeAlias = str          # label string for a single harmonic
Period: TypeAlias = int          # period k: fires at positions k, 2k, 3k, …
CompoundLabel: TypeAlias = str   # sep-joined labels active at a position
PeriodToLabel: TypeAlias = Dict[Period, Label]
PosToCompound: TypeAlias = Dict[int, CompoundLabel]


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class PeriodicConfig:
    """Configure the generation of one periodic pattern."""

    # Number of harmonics. With the default periods (None), the k-th harmonic
    # fires at k, 2k, 3k, … for k in 1..n; with explicit `periods`, n is how
    # many periods that set holds.
    n: int
    # n strings, or int n to auto-generate n random labels. Assigned in
    # ascending-period order: labels[i] belongs to the i-th smallest period.
    labels: Collection[Label] | int
    seed: int
    # Separator between active labels in compound output; must not appear in
    # any label.
    sep: str = "|"
    # Explicit periods exist because the default 1..n makes length the step
    # function lcm(1..n): lcm(1..10) == lcm(1..9) == 2520, then n=11 leaps to
    # 27,720 positions (~341k tokens, past every context window). None selects
    # the consecutive-integer pathway, whose generated bytes are pinned by
    # tests/induction/test_golden_quizzes.py.
    periods: Tuple[int, ...] | None = None
    # The sequence length `periods` is expected to produce. Omit it and the
    # periods must be pairwise coprime (lcm == product, a longer EXTENSIONAL
    # listing). Supply it and coprimality is not required -- lcm(periods)
    # must equal it exactly, letting a divisor set add harmonics while
    # pinning the length (a longer INTENSIONAL rule list, fixed listing).
    # Either way, a periods/length mismatch fails construction rather than
    # silently generating the wrong quiz.
    expect_seq_len: int | None = None

    def __post_init__(self) -> None:
        if self.n < 1:
            raise ValueError("n must be positive.")
        if self.periods is not None:
            periods = tuple(int(p) for p in self.periods)
            if len(periods) != self.n:
                raise ValueError(
                    f"Number of periods ({len(periods)}) must equal n ({self.n})."
                )
            if len(set(periods)) != len(periods):
                raise ValueError(f"Periods must be distinct, got {periods}.")
            if any(p < 1 for p in periods):
                raise ValueError(f"Periods must be positive, got {periods}.")
            if self.expect_seq_len is None:
                # Pairwise coprimality makes lcm(periods) == prod(periods),
                # so length is a product the caller dials directly.
                for i, a in enumerate(periods):
                    for b in periods[i + 1:]:
                        if gcd(a, b) != 1:
                            raise ValueError(
                                f"Periods must be pairwise coprime; gcd({a}, {b}) = {gcd(a, b)}. "
                                "Without coprimality lcm(periods) < prod(periods) and the "
                                "sequence length is no longer the product you asked for. "
                                "Pass expect_seq_len=<length> to use a non-coprime set on "
                                "purpose (the divisor pathway)."
                            )
            else:
                # Divisor pathway: periods deliberately share factors so lcm
                # stays put while adding harmonics grows the rule list.
                actual = lcm(*periods)
                if actual != self.expect_seq_len:
                    raise ValueError(
                        f"lcm(periods) is {actual}, not the declared expect_seq_len "
                        f"{self.expect_seq_len}. Every period must divide the declared "
                        "length (and together they must reach it) or the extensional "
                        "listing silently changes size, which is the one thing this "
                        "pathway exists to hold fixed."
                    )
            object.__setattr__(self, "periods", periods)
        elif self.expect_seq_len is not None:
            raise ValueError(
                "expect_seq_len only means something alongside an explicit `periods` "
                "set; on the default 1..n pathway the length is lcm(1..n) by definition."
            )
        if isinstance(self.labels, int):
            if self.labels != self.n:
                raise ValueError(
                    f"When labels is int it must equal n ({self.n}), got {self.labels}."
                )
            # min_length=2: labels are always multi-character, even at small
            # n where the information-theoretic minimum would allow single
            # letters.
            object.__setattr__(
                self,
                "labels",
                random_labels(
                    self.labels, self.seed, charset=_LABEL_CHARSET, min_length=2
                ),
            )
        else:
            object.__setattr__(self, "labels", tuple(self.labels))
        if len(self.labels) != self.n:
            raise ValueError(
                f"Number of labels ({len(self.labels)}) must equal n ({self.n})."
            )
        if len(set(self.labels)) != len(self.labels):
            # A duplicate label gives a single prompt two contradictory
            # ground truths; this guards explicit label lists.
            raise ValueError(f"Labels must be distinct, got {tuple(self.labels)}.")
        for lbl in self.labels:
            if self.sep in lbl:
                raise ValueError(
                    f"Label '{lbl}' contains the separator '{self.sep}'."
                )


# Lowercase letters only, not letters+digits: free in prompt length at every
# count this benchmark uses, but buys READABILITY. Exact-string distinctness
# is not case-folded, so a mixed-case charset could draw visually confusable
# labels like "aQ"/"Aq"; excluding digits keeps a label from reading as a
# position number ("Every 3 positions write 3x."). The charset must also
# contain no separator character, or a label holding `sep` would split into
# two on render -- enforced in `PeriodicConfig.__post_init__`, not assumed.
_LABEL_CHARSET: str = string.ascii_lowercase


# ---------------------------------------------------------------------------
# Sequence generation
# ---------------------------------------------------------------------------

def _periods_of(config: PeriodicConfig) -> Tuple[int, ...]:
    """Return the harmonic periods this config asks for, in ascending order.

    The only point where the default 1..n and explicit-``periods`` pathways
    differ; everything downstream is shared verbatim.

    Parameters
    ----------
    config : PeriodicConfig
        Configuration specifying the harmonic periods.

    Returns
    -------
    Tuple[int, ...]
        Harmonic periods in ascending order.
    """
    if config.periods is None:
        return tuple(range(1, config.n + 1))
    return tuple(sorted(config.periods))


def _seq_len_of(config: PeriodicConfig) -> int:
    """Return the sequence length: the lcm of the config's harmonic periods."""
    return lcm(*_periods_of(config))


def generate_sequence(config: PeriodicConfig) -> Tuple[PeriodToLabel, PosToCompound]:
    """Generate the period-to-label and position-to-compound mappings.

    Covers positions 1..lcm(periods), each mapped to the sep-joined labels whose
    periods divide it, in ascending period order (``labels[i]`` belonging to the
    i-th smallest period).

    Parameters
    ----------
    config : PeriodicConfig
        Configuration supplying the periods, labels, and separator.

    Returns
    -------
    Tuple[PeriodToLabel, PosToCompound]
        Period-to-label and position-to-compound mappings.
    """
    periods = _periods_of(config)
    period_to_label: PeriodToLabel = {
        k: config.labels[i] for i, k in enumerate(periods)
    }
    seq_len = _seq_len_of(config)
    pos_to_compound: PosToCompound = {
        pos: config.sep.join(
            period_to_label[k] for k in periods if pos % k == 0
        )
        for pos in range(1, seq_len + 1)
    }
    return period_to_label, pos_to_compound


# ---------------------------------------------------------------------------
# Prompt renderers
# ---------------------------------------------------------------------------

def _render_intensional(period_to_label: PeriodToLabel) -> str:
    """Render the harmonic rules as human-readable text."""
    return "".join(
        f"Every {k} positions write {label}.\n"
        for k, label in sorted(period_to_label.items())
    )


def _render_extensional(pos_to_compound: PosToCompound) -> str:
    """Render the sequence as a position-indexed lookup table."""
    return "".join(
        f"Position {pos}: {compound}.\n"
        for pos, compound in sorted(pos_to_compound.items())
    )


# ---------------------------------------------------------------------------
# Information conditions
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Contexts:
    """The two rendered context bodies one sequence produces.

    Bundles :func:`_render_intensional`'s and :func:`_render_extensional`'s
    output for a single query's generation pass, so a :class:`Condition`'s
    ``context`` callable can pick whichever body (or neither) its arm shows,
    without every call site re-deriving both renders by hand.
    """

    #: The compact rule list ("Every 3 positions write gerbil.").
    intensional: str
    #: The enumerated position -> compound-label table ("Position 6: ...").
    extensional: str


@dataclass(frozen=True)
class Condition:
    """One information condition: which context it shows, and how.

    match_tokens_to: name of another condition (without its own
    ``match_tokens_to``) whose rendered token count this arm must exactly
    match via whitespace padding; ``None`` renders plainly.
    omit_range: if ``True``, renders from ``prompter.range_free_template``
    instead of ``prompter.template``, and the rendered text is verified to
    contain none of ``RANGE_KEYS``'s values.
    """

    context: Callable[[Contexts], str]
    match_tokens_to: Optional[str] = None
    omit_range: bool = False


# The single declaration of this benchmark's information conditions -- every
# consumer derives from THIS mapping rather than restating the arm names.
# MappingProxyType, not a plain dict: it is a shared module-level default, and
# a caller mutating a plain dict in place would change every other caller's
# default underneath it.
CONDITIONS: Mapping[str, Condition] = MappingProxyType({
    # The compact rule list.
    "intens": Condition(context=lambda c: c.intensional),
    # The full position-by-position enumeration; usually more tokens than
    # intens, the pairing the noise arm isolates length from.
    "extens": Condition(context=lambda c: c.extensional),
    # intens's text, whitespace-padded until the rendered prompt hits
    # extens's token count -- a length-matched control arm, so a gap between
    # this and intens cannot be explained by prompt length alone.
    "noise_intens": Condition(context=lambda c: c.intensional, match_tokens_to="extens"),
    # No context, and a range-free question: on the default 1..n pathway the
    # period-1 harmonic's answer IS seq_len, so the range-stating question
    # the other arms use would print that answer directly into the one arm
    # meant to measure the floor with no positive information.
    "zero": Condition(context=lambda c: "", omit_range=True),
})


# The query-substitution keys naming the position range ("1 through
# $seq_len"). An ``omit_range`` condition's RENDERED prompt is verified to
# contain none of these keys' values -- checking the rendered text, not just
# the template, so a template that names the key elsewhere still gets caught.
# A generator that never emits these keys (``tof_membership_query_gen``,
# which states a position, not a range) is vacuously range-free.
RANGE_KEYS: Tuple[str, ...] = ("seq_len",)


# ---------------------------------------------------------------------------
# Core prompt generation
# ---------------------------------------------------------------------------

def _resolve_arm_template(name: str, condition: Condition, prompter: Prompter) -> string.Template:
    """Return the template `name`'s condition renders from.

    ``omit_range`` conditions render from ``prompter.range_free_template``;
    every other condition renders from ``prompter.template``. No silent fallback to
    ``prompter.template``, since that fallback is exactly the leak an
    ``omit_range`` condition exists to avoid.

    Parameters
    ----------
    name : str
        Name of the information condition.
    condition : Condition
        Information condition being rendered.
    prompter : Prompter
        Prompt templates and query generator.

    Returns
    -------
    string.Template
        Template selected for the condition.

    Raises
    ------
    ValueError
        If `condition` is ``omit_range=True`` and ``prompter.range_free_template`` is
        ``None``.
    """
    if not condition.omit_range:
        return prompter.template
    if prompter.range_free_template is None:
        raise ValueError(
            f"condition {name!r} has omit_range=True but "
            "prompter.range_free_template is None: a range-omitting "
            "condition must be given its own range-free question. Falling "
            "back to prompter.template would render the ordinary, "
            "range-stating question -- exactly the leak this condition "
            "exists to remove."
        )
    return prompter.range_free_template


def _verify_no_range_leak(name: str, query: Dict[str, str], rendered: str) -> None:
    """Raise if `rendered` reveals any of ``RANGE_KEYS``'s values from `query`.

    Checked against the rendered prompt, not the template used to build it
    (see ``RANGE_KEYS``). Naming the offending key and its value on failure.

    Parameters
    ----------
    name : str
        Name of the information condition.
    query : Dict[str, str]
        Query substitutions whose range values must remain hidden.
    rendered : str
        Rendered prompt to inspect.
    """
    for key in RANGE_KEYS:
        if key in query and str(query[key]) in rendered:
            raise ValueError(
                f"condition {name!r} is omit_range=True (its prompt must "
                f"never reveal the position range) but its rendered prompt "
                f"still contains {key}={query[key]!r}: the supplied "
                "range_free_template leaks the very thing it exists to omit."
            )


def get_periodic_prompts(
    config: PeriodicConfig,
    prompter: Prompter,
    *,
    tokenizer: Tokenizer,
    conditions: Mapping[str, Condition] = CONDITIONS,
) -> Iterable[RenderedQuery]:
    """Render every information condition of every query, in one loop.

    For each query :func:`generate_sequence` (via ``prompter.query_gen``)
    produces, renders every entry of `conditions` and yields one
    :class:`~smolbench.induction._common.RenderedQuery` carrying all of them.
    Rendering happens in two stages per query: first every condition without
    ``match_tokens_to`` (recording its rendered prompt and token count), then
    every condition with one, padded against the already-recorded target
    condition's count.

    Parameters
    ----------
    config : PeriodicConfig
        Configuration for the periodic sequence.
    prompter : Prompter
        Prompt templates and query generator.
    tokenizer : Tokenizer
        Must be the model under test's own, since it defines every padded arm's token
        target.
    conditions : Mapping[str, Condition], optional
        Information conditions to render.

    Yields
    ------
    RenderedQuery
        One rendered query containing prompts and token counts for every condition.

    Raises
    ------
    ValueError
        Once, before any query is rendered, if some condition's ``match_tokens_to`` names a
        condition absent from `conditions` or one that is itself padded (a padded arm's own
        count isn't available yet to pad against); propagated from
        :func:`~smolbench.evals.tokenization.token_matched_noise_prompt` when the noise arm's
        precondition fails for some query (its extensional prompt is not strictly longer, in
        tokens, than its intensional one -- deliberately not caught here, so the confound stays
        out of collected data rather than silently shipping a control identical to the arm it
        controls for); or from :func:`_resolve_arm_template`/:func:`_verify_no_range_leak` for an
        ``omit_range`` condition missing its template or leaking a range key.
    """
    # Validated once, before any query is rendered: a bad `match_tokens_to`
    # is a construction-time mistake in `conditions`, not something that
    # should surface only after partial work on the first query.
    for name, condition in conditions.items():
        target = condition.match_tokens_to
        if target is None:
            continue
        if target not in conditions:
            raise ValueError(
                f"condition {name!r}: match_tokens_to={target!r} names a "
                f"condition not present in conditions ({sorted(conditions)})."
            )
        if conditions[target].match_tokens_to is not None:
            raise ValueError(
                f"condition {name!r}: match_tokens_to target {target!r} is "
                f"itself padded (match_tokens_to={conditions[target].match_tokens_to!r}). "
                "A padded arm's own count is not available to pad against "
                "-- it depends on the very pad search that has not run yet "
                "-- and a chain of padded arms has no count to bottom out on."
            )

    period_to_label, pos_to_compound = generate_sequence(config)

    contexts = Contexts(
        intensional=_render_intensional(period_to_label),
        extensional=_render_extensional(pos_to_compound),
    )

    # Probe the pad atom once, not per query: it depends only on the tokenizer.
    unit: str = choose_whitespace_unit(tokenizer)

    # Split once: stage membership depends only on `match_tokens_to`, not on
    # where an entry sits in `conditions`.
    unpadded = [(n, c) for n, c in conditions.items() if c.match_tokens_to is None]
    padded = [(n, c) for n, c in conditions.items() if c.match_tokens_to is not None]

    for query, answer in prompter.query_gen(period_to_label, pos_to_compound, config.seed):
        prompts: Dict[str, str] = {}
        token_counts: Dict[str, int] = {}

        # Stage 1: every condition that renders plainly, with no pad target
        # to wait on.
        for name, condition in unpadded:
            template = _resolve_arm_template(name, condition, prompter)
            rendered = template.safe_substitute(
                build_substitution(query, condition.context(contexts))
            )
            if condition.omit_range:
                _verify_no_range_leak(name, query, rendered)
            prompts[name] = rendered
            token_counts[name] = tokenizer.count(rendered)

        # Stage 2: every condition padded to a stage-1 condition's count.
        # `context_renderer` renders exactly as stage 1 above, so the two
        # differ only in the appended whitespace pad.
        for name, condition in padded:
            template = _resolve_arm_template(name, condition, prompter)
            target_count = token_counts[condition.match_tokens_to]
            rendered = token_matched_noise_prompt(
                context_renderer(prompter, query, template=template),
                condition.context(contexts),
                target_count,
                tokenizer,
                unit=unit,
            )
            if condition.omit_range:
                _verify_no_range_leak(name, query, rendered)
            prompts[name] = rendered
            # NOT tokenizer.count(rendered) again: the pad search already
            # verified this hits target_count exactly, and the tokenizer ran
            # during that search regardless of whether anyone reads the count.
            token_counts[name] = target_count

        # Emit in `conditions`'s own order, not the stage-1/stage-2 split
        # order used to build the two dicts above.
        yield RenderedQuery(
            prompts={name: prompts[name] for name in conditions},
            token_counts={name: token_counts[name] for name in conditions},
            answer=answer,
        )


# ---------------------------------------------------------------------------
# Quiz wrappers
# ---------------------------------------------------------------------------

def get_periodic_quiz(
    config: PeriodicConfig,
    prompter: Prompter,
    *,
    tokenizer: Tokenizer,
    conditions: Mapping[str, Condition] = CONDITIONS,
) -> Dict[str, Quiz]:
    """Wrap :func:`get_periodic_prompts` as ``ToF`` quizzes, keyed by condition name.

    A ``dict``, not a positional tuple: a caller reads a specific arm by name
    (``quizzes["extens"]``), so reordering `conditions` can never silently
    relabel an existing caller's arms.
    """
    return quizzes_from_prompts(
        get_periodic_prompts(config, prompter, tokenizer=tokenizer, conditions=conditions),
        ToF,
        conditions,
    )


def get_periodic_numeric_quiz(
    config: PeriodicConfig,
    prompter: Prompter,
    *,
    tokenizer: Tokenizer,
    conditions: Mapping[str, Condition] = CONDITIONS,
) -> Dict[str, Quiz]:
    """Wrap :func:`get_periodic_prompts` as ``Numeric`` quizzes, keyed by condition name.

    See :func:`get_periodic_quiz`'s docstring for the return shape rationale;
    this is the same wrapper over ``Numeric`` instead of ``ToF``.
    """
    return quizzes_from_prompts(
        get_periodic_prompts(config, prompter, tokenizer=tokenizer, conditions=conditions),
        Numeric,
        conditions,
    )


# ---------------------------------------------------------------------------
# Built-in query generators
# ---------------------------------------------------------------------------

# tof_membership_query_gen samples at most this many queries of EACH polarity
# per quiz, so quiz size stays fixed as n grows: a replication design is
# powered around fixed question counts and must never silently change it.
MAX_QUERIES_PER_POLARITY: int = 10


def tof_membership_query_gen(
    period_to_label: PeriodToLabel,
    pos_to_compound: PosToCompound,
    seed: int,
) -> Iterable[Tuple[Dict[str, str], bool]]:
    """Yield True/False queries of the form "Does label appear at position pos?"

    Yields ``({"pos": ..., "label": ...}, answer)`` pairs: at most
    ``MAX_QUERIES_PER_POLARITY`` True queries and equally many False ones (fewer
    if the pattern admits fewer of either polarity), sampled without replacement
    under ``seed``; period-1 labels are excluded as trivially True. Both mappings
    come from :func:`generate_sequence`.
    """
    rng = np.random.default_rng(seed)

    true_qs: list = []
    false_qs: list = []

    # Hoisted: the (period, label) ordering is position-independent.
    period_labels = sorted(period_to_label.items())
    for pos in sorted(pos_to_compound.keys()):
        for period, label in period_labels:
            if period == 1:
                continue  # true for every position -- skip this trivial query
            entry = ({"pos": str(pos), "label": label}, pos % period == 0)
            (true_qs if pos % period == 0 else false_qs).append(entry)

    n = min(len(true_qs), len(false_qs), MAX_QUERIES_PER_POLARITY)
    if n == 0:
        # Too small to admit both polarities -> empty quiz, not an error
        # (legitimate for tiny test configs).
        return

    # True block then False block, unshuffled: each query is a separate
    # prompt, so order leaks nothing between questions.
    for idx in rng.choice(len(true_qs), n, replace=False):
        yield true_qs[idx]
    for idx in rng.choice(len(false_qs), n, replace=False):
        yield false_qs[idx]


def numeric_count_query_gen(
    period_to_label: PeriodToLabel,
    pos_to_compound: PosToCompound,
    seed: int,
) -> Iterable[Tuple[Dict[str, str], int]]:
    """Yield count queries of the form "How many positions 1..seq_len contain label?"

    Yields one ``({"label": ..., "seq_len": ...}, answer)`` pair per label,
    the answer being floor(seq_len / period) -- always exact, since seq_len
    is the lcm of the harmonic periods on every pathway.

    Deterministic and ignores `seed`: the parameter stays so this generator
    stays substitutable for the sibling :func:`tof_membership_query_gen`
    under ``Prompter.query_gen``'s one shared protocol. A seed still reaches
    the output indirectly, since ``PeriodicConfig`` draws the labels with it.
    """
    seq_len = max(pos_to_compound.keys())
    for period, label in sorted(period_to_label.items()):
        yield {"label": label, "seq_len": str(seq_len)}, seq_len // period


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    template = string.Template(
        "Context:\n"
        "---\n"
        "There is a counting game. Count positions starting from 1. "
        "At each position write down words according to the following rules:\n"
        "$positive_info\n"
        "Query:\n"
        "How many of the positions 1 through $seq_len include '$label'? "
        "Answer with a single integer."
    )

    # The `zero` condition's range-free counterpart of `template` above (see
    # `CONDITIONS`'s "zero" entry for why it needs this rather than `template`
    # itself).
    range_free_template = string.Template(
        template.template.replace(" 1 through $seq_len", "")
    )

    cfg = PeriodicConfig(
        n=3,
        labels=["fizz", "buzz", "gerbil"],
        seed=42,
    )

    # No served model here, so measure with a fixed tiktoken encoding; a real
    # run passes the model under test's own tokenizer.
    demo_tokenizer = TiktokenTokenizer("cl100k_base")

    for rendered in get_periodic_prompts(
        cfg,
        Prompter(template, numeric_count_query_gen, range_free_template=range_free_template),
        tokenizer=demo_tokenizer,
    ):
        print("-- intensional --")
        print(rendered.prompts["intens"])
        print("-- extensional --")
        print(rendered.prompts["extens"])
        print("-- zero --")
        print(rendered.prompts["zero"])
        print("answer:", rendered.answer)
        print(
            "token counts -- intens:", rendered.token_counts["intens"],
            "extens:", rendered.token_counts["extens"],
            "noise_intens:", rendered.token_counts["noise_intens"],
            "zero:", rendered.token_counts["zero"],
        )
        print()
