"""Guard the deduction study's pinned theorem set, offline.

The pin is underivable from a clean clone (seeded sample over an S3-only sidecar),
and a one-theorem pool change reshuffles all 300 silently, so pin the digest.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import re
import subprocess
import sys

import pytest

from tests._paths import (LEAN_MINI_POSTCUTOFF as POSTCUTOFF, NOTEBOOKS,
                         REPO_ROOT, SCRIPTS)

MANIFEST = NOTEBOOKS / "deduction" / "pinned_theorems.json"

#: The pinned set's identity. Both are load-bearing: the count alone would
#: pass a swap of one theorem for another, and the digest alone would not
#: localize a size change.
EXPECTED_COUNT = 300
EXPECTED_SHA256 = "292194deb832f75ae2f4008a7d597e4d6ac765ff9c0c4e4a31b7eeab377e5b36"

#: Corpus provenance. Pinned so a corpus swap cannot happen silently -- the
#: recency finding (notebooks/deduction/README.md, "Corpus date vs. model
#: cutoffs") is stated ENTIRELY in terms of this commit's trace date, so a
#: different corpus invalidates that section.
EXPECTED_COMMIT = "fe4454af900584467d21f4fd4fe951d29d9332a7"
EXPECTED_CREATION_TIME = "2024-03-24 23:38:32.469290"

#: The post-cutoff fixture's own provenance, for the freshly-emitted manifest.
FIXTURE_COMMIT = "2ca39e62989124794bd8405bb2e60805f63d37bc"
FIXTURE_CREATION_TIME = "2026-08-30 15:43:26.000000"
FIXTURE_NAMES = ("Mini.theoremA", "Mini.theoremB")


@pytest.fixture(scope="module")
def manifest() -> dict:
    return json.loads(MANIFEST.read_text())


@pytest.fixture(scope="module")
def emitted(tmp_path_factory, audit) -> dict:
    """A manifest freshly emitted by `--emit-manifest`, offline, from the fixture.

    The committed manifest claims it was "Generated by
    scripts/results/audit_lean_pinning.py --emit-manifest"; running the emitter
    against a fixture corpus is what makes that claim checkable without the
    ~700 MB dataset or any AWS call.
    """
    tmp = tmp_path_factory.mktemp("emit")
    sidecar = tmp / "replay_passing_random_val.jsonl"
    sidecar.write_text("".join(
        json.dumps({"full_name": n, "verdict": "success"}) + "\n" for n in FIXTURE_NAMES))
    out = tmp / "pinned_theorems.json"
    assert audit.main([
        "--offline", "--emit-manifest", str(out),
        "--val-json", str(POSTCUTOFF / "random" / "val.json"),
        "--replay-jsonl", str(sidecar),
        "--metadata", str(POSTCUTOFF / "metadata.json"),
        "--limit", "2", "--seed", "0"]) == 0
    return json.loads(out.read_text())


#: ``(fixture name, expectations)``. The committed manifest is the old study's
#: record; the emitted one proves the emitter still produces that exact shape.
MANIFEST_CASES = [
    pytest.param("manifest", {
        "count": EXPECTED_COUNT, "sha256": EXPECTED_SHA256,
        "commit": EXPECTED_COMMIT, "creation_time": EXPECTED_CREATION_TIME,
        "derivation": ("replay_passing", "novel_premises", "val"),
        "shape": (300, 0, 805), "postcutoff": None}, id="committed"),
    pytest.param("emitted", {
        "count": 2, "sha256": None,
        "commit": FIXTURE_COMMIT, "creation_time": FIXTURE_CREATION_TIME,
        "derivation": ("replay_passing", "random", "val"),
        "shape": (2, 0, 2), "postcutoff": "2026-07-31"}, id="emitted"),
]


@pytest.mark.parametrize("which,expected", MANIFEST_CASES)
def test_pinned_manifest_identity(request, which, expected):
    """Membership digest, corpus provenance, and the recorded draw recipe."""
    manifest = request.getfixturevalue(which)
    names = manifest["full_names"]
    assert manifest["count"] == expected["count"] == len(names)
    assert len(set(names)) == expected["count"], "pinned set contains duplicates"
    assert names == sorted(names), "full_names must be stored sorted"
    digest = hashlib.sha256("\n".join(names).encode()).hexdigest()
    assert digest == manifest["sha256_of_sorted_full_names"]
    if expected["sha256"] is not None:
        assert digest == expected["sha256"]

    corpus = manifest["corpus"]
    assert corpus["from_repo"]["commit"] == expected["commit"]
    assert corpus["creation_time"] == expected["creation_time"]
    assert corpus["from_repo"]["url"].endswith("leanprover-community/mathlib4")
    # The corpus block carries metadata.json verbatim, so a post-cutoff corpus's
    # provenance rides along and a reader can check T without the dataset.
    if expected["postcutoff"] is None:
        assert "postcutoff" not in corpus
    else:
        assert corpus["postcutoff"]["target_date"] == expected["postcutoff"]
        assert corpus["postcutoff"]["new_commit"] == expected["commit"]

    d = manifest["derivation"]
    assert (d["source"], d["kind"], d["split"]) == expected["derivation"]
    assert (d["limit"], d["seed"], d["pool_size"]) == expected["shape"]


def test_slug_theorem_maps_pinned_names_injectively():
    """The lossy on-disk slug must not collide two distinct pinned theorems."""
    spec = importlib.util.spec_from_file_location(
        "_audit", SCRIPTS / "results" / "audit_lean_pinning.py"
    )
    audit = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(audit)

    from smolbench.deduction.lean import runner

    names = json.loads(MANIFEST.read_text())["full_names"]
    assert len({audit.slug_theorem(n) for n in names}) == len(names)
    assert all(audit.slug_theorem(n) == runner.slug_theorem(n) for n in names)
    assert any(re.search(r"[?']", n) for n in names)


@pytest.fixture(scope="module")
def audit():
    spec = importlib.util.spec_from_file_location(
        "_audit", SCRIPTS / "results" / "audit_lean_pinning.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_layer4_counts_a_missing_prompt_artifact_as_divergent(audit):
    """A cell no lane spooled a prompt for must not certify as byte-identical."""
    lanes = audit.LANES
    shared = {lane: {"thm|stepk-1": "etag-a", "thm|hint-2": "etag-b"} for lane in lanes}
    assert audit.divergent_prompt_cells({"thm|stepk-1", "thm|hint-2"}, shared) == set()
    assert audit.divergent_prompt_cells({"thm|absent"}, shared) == {"thm|absent"}
    one_missing = {**shared, lanes[0]: {"thm|hint-2": "etag-b"}}
    assert audit.divergent_prompt_cells({"thm|stepk-1"}, one_missing) == {"thm|stepk-1"}
    differing = {**shared, lanes[1]: {**shared[lanes[1]], "thm|stepk-1": "etag-z"}}
    assert audit.divergent_prompt_cells({"thm|stepk-1"}, differing) == {"thm|stepk-1"}


def test_fetch_recovery_tolerates_absence_but_propagates_real_errors(audit):
    """Only "no such key" becomes an empty lane; AccessDenied must surface."""
    class _Err(Exception):
        def __init__(self, response):
            self.response = response

    class _S3:
        def __init__(self, response):
            self.response = response

        def get_object(self, **kwargs):
            raise _Err(self.response)

    missing = {"Error": {"Code": "NoSuchKey"}, "ResponseMetadata": {"HTTPStatusCode": 404}}
    assert audit.fetch_recovery(_S3(missing)) == {lane: set() for lane in audit.LANES}
    denied = {"Error": {"Code": "AccessDenied"}, "ResponseMetadata": {"HTTPStatusCode": 403}}
    with pytest.raises(_Err):
        audit.fetch_recovery(_S3(denied))


def test_expected_shape_constants_are_a_coherent_definition():
    """`runner`'s EXPECTED_* are the ONE definition; pin their shape, not their values.

    13-20: this used to assert the literal ``(300, 944, 300)`` in a test whose
    stated subject is single-sourcing. That is the wrong pin in both
    directions -- a legitimate re-baselining to a smaller post-cutoff pool
    (say 250/800/250) fails HERE, for a reason that has nothing to do with
    single-sourcing, while the tuple would still pass if a consumer had
    stopped reading these constants at all. The pinned VALUE of the drawn
    theorem set lives where it belongs, in `EXPECTED_COUNT` /
    `EXPECTED_SHA256` above, over the actual manifest.
    """
    from smolbench.deduction.lean import runner

    shape = (runner.EXPECTED_THEOREMS, runner.EXPECTED_CELLS,
             runner.EXPECTED_SANITY_ROWS)
    assert all(isinstance(v, int) and v > 0 for v in shape), shape
    assert runner.EXPECTED_SANITY_ROWS == runner.EXPECTED_THEOREMS, (
        "one sanity row per theorem is the sweep's invariant"
    )
    assert runner.EXPECTED_CELLS >= runner.EXPECTED_THEOREMS, (
        "each theorem yields at least one cell"
    )


@pytest.mark.parametrize("path,flag,attr", [
    ("results/audit_lean_pinning.py", "--expect-theorems", "EXPECTED_THEOREMS"),
    ("results/audit_lean_pinning.py", "--expect-cells", "EXPECTED_CELLS"),
    ("results/audit_run_completeness.py", "--expect-cells", "EXPECTED_CELLS"),
    ("deduction/merge_lean_shards.py", "--expect-cells", "EXPECTED_CELLS"),
    ("deduction/merge_lean_shards.py", "--expect-sanity", "EXPECTED_SANITY_ROWS"),
    ("deduction/split_lean_run_into_shards.py", "--limit", "EXPECTED_THEOREMS"),
])
def test_every_consumer_shows_runners_expected_default(path, flag, attr):
    """Each consumer's ``--help`` must show `runner`'s value, not a literal of its own.

    Checked through ``--help`` rather than by importing: a drift surfaces as a
    visible default mismatch, and ``--help`` also proves the shared import is
    not import-time-fatal on a box where these scripts run.

    13-20: was a loop with a bare ``continue`` for consumers that live in a
    later stack slice, so a slice missing ALL of them passed vacuously and
    silently. Parametrised and `pytest.skip`ped instead, so an absent consumer
    is visible in the run summary as a SKIP and cannot be mistaken for a check
    that ran.
    """
    from smolbench.deduction.lean import runner

    script = SCRIPTS / path
    if not script.exists():
        pytest.skip(f"{path} lives in a later stack slice")
    want = getattr(runner, attr)
    proc = subprocess.run(
        [sys.executable, str(script), "--help"], capture_output=True,
        text=True, cwd=str(REPO_ROOT), timeout=300,
        env={**os.environ, "PYTHONPATH": str(REPO_ROOT)})
    assert proc.returncode == 0, proc.stderr
    assert flag in proc.stdout, f"{path} lacks {flag}\n{proc.stdout}"
    assert str(want) in proc.stdout, f"{path} {flag} does not show {want}\n{proc.stdout}"
