"""Look up traced Lean premises, their source text, and their derivation edges.

`body_with_proof` slices source through the next declaration so theorem proofs
survive the signature-only corpus record.

`referenced_premises` gives the derivation edges the `hint:3+` rungs expand.
It prefers the LeanDojo trace (the premises each tactic of a theorem's proof
actually used, the same data the MPI is built from) and falls back to
namespace-aware name resolution over the declaration source for premises
without a trace (definitions, instances, term-mode proofs).
"""

from __future__ import annotations

import heapq
import json
import os
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterable

from .corpus import data_root, metadata


@dataclass(frozen=True)
class Premise:
    """A declaration in the traced repository.

    ``full_name`` is the join key from lighter ``corpus.TracedTactic.premises``
    records to `lookup`, which `context.py` uses to resolve them.
    """

    #: Fully-qualified declaration name.
    full_name: str
    #: Corpus source text.
    code: str
    #: 1-indexed start ``(line, column)``.
    start: tuple[int, int]
    #: End ``(line, column)``.
    end: tuple[int, int]
    #: Corpus declaration kind.
    kind: str
    #: Corpus-relative source path.
    file_path: str


@lru_cache(maxsize=1)
def _index() -> dict[str, Premise]:
    """Load the ~5s cached ``corpus.jsonl`` index."""
    path = data_root() / "corpus.jsonl"
    idx: dict[str, Premise] = {}
    with path.open() as f:
        for line in f:
            rec = json.loads(line)
            for p in rec["premises"]:
                fn = p["full_name"]
                # Keep the first collision.
                if fn in idx:
                    continue
                idx[fn] = Premise(
                    full_name=fn,
                    code=p["code"],
                    start=tuple(p["start"]),  # type: ignore[arg-type]
                    end=tuple(p["end"]),  # type: ignore[arg-type]
                    kind=p["kind"],
                    file_path=rec["path"],
                )
    return idx


@lru_cache(maxsize=1)
def _file_rank() -> dict[str, int]:
    """Import-order rank of every corpus file: a file ranks after all it imports.

    Kahn's algorithm over ``corpus.jsonl``'s ``imports`` with sorted-path
    tie-breaks, so the order is total and machine-independent. A file that
    imports a path absent from the corpus ignores that edge.
    """
    path = data_root() / "corpus.jsonl"
    imports: dict[str, list[str]] = {}
    with path.open() as f:
        for line in f:
            rec = json.loads(line)
            imports.setdefault(rec["path"], list(rec.get("imports") or []))
    indeg = {p: 0 for p in imports}
    users: dict[str, list[str]] = {p: [] for p in imports}
    for p, deps in imports.items():
        for d in deps:
            if d in imports and d != p:
                indeg[p] += 1
                users[d].append(p)
    ready = sorted(p for p, n in indeg.items() if n == 0)
    rank: dict[str, int] = {}
    heapq.heapify(ready)
    while ready:
        p = heapq.heappop(ready)
        rank[p] = len(rank)
        for u in users[p]:
            indeg[u] -= 1
            if indeg[u] == 0:
                heapq.heappush(ready, u)
    for p in sorted(imports):  # cycles (should not occur): append deterministically
        rank.setdefault(p, len(rank))
    return rank


def library_order(ps: Iterable[Premise]) -> list[Premise]:
    """Sort premises as Mathlib builds them: import order, then line, then name.

    Every dependency precedes its dependents (a file can only use what it
    imports or what comes earlier in itself), so this is a topological order
    of the derivation without marking which entries are the roots.

    Parameters
    ----------
    ps : Iterable[Premise]

    Returns
    -------
    list[Premise]
    """
    rank = _file_rank()
    return sorted(ps, key=lambda p: (rank.get(p.file_path, len(rank)), p.start, p.full_name))


# ---------------------------------------------------------------------------
# Checked signatures: declarations the corpus export omits
# ---------------------------------------------------------------------------
#
# LeanDojo's ``corpus.jsonl`` records only declarations with their own source
# span. Lemmas generated by ``@[to_additive]``, constructors, structure
# projections and macro-made definitions are cited by traces but have no
# record. ``#print`` through the built Mathlib states each one's kind and
# type, and a short delegating body; the sidecar caches that per corpus.

#: ``#print`` header: ``[attrs] [modifiers] <kind> <name>[.{univs}] : <type...>``.
_CHECKED_KIND_RE = re.compile(
    r"^(?:@\[[^\]]*\]\s*)*(?:(?:private|protected|noncomputable|unsafe|partial)\s+)*"
    r"(?P<kind>theorem|def|abbrev|constructor|structure|inductive|class|instance|"
    r"axiom|opaque|recursor|quot)\s+(?P<name>[^\s:]+?)(?:\.\{[^}]*\})?\s+:\s(?P<rest>.*)$"
)
_LEAN_MSG_RE = re.compile(r"^\S+\.lean:\d+:\d+: (?:error|warning|info)")

#: A delegating body longer than this is elaborated noise, not source.
_CHECKED_BODY_MAX = 600


def checked_signatures_path() -> Path:
    """``<data_root>/checked_signatures.json``."""
    return data_root() / "checked_signatures.json"


@lru_cache(maxsize=1)
def _checked() -> dict[str, dict]:
    """Load the checked-signature sidecar, or ``{}`` when absent."""
    path = checked_signatures_path()
    return json.loads(path.read_text()) if path.exists() else {}


def module_of(def_path: str) -> str | None:
    """Lean module name for a corpus-relative ``.lean`` path.

    ``Mathlib/A/B.lean`` is ``Mathlib.A.B``; a dependency under
    ``.lake/packages/<pkg>/`` drops that prefix and a ``src/lean/`` layer
    (``.lake/packages/lean4/src/lean/Init/Prelude.lean`` is ``Init.Prelude``).

    Parameters
    ----------
    def_path : str

    Returns
    -------
    str | None
        None for a path that is not a ``.lean`` file.
    """
    if not def_path.endswith(".lean"):
        return None
    parts = def_path[: -len(".lean")].split("/")
    if parts[:2] == [".lake", "packages"] and len(parts) > 3:
        parts = parts[3:]
        if parts[:2] == ["src", "lean"]:
            parts = parts[2:]
    return ".".join(parts)


def missing_trace_premises(
    kind: str = "random", splits: tuple[str, ...] = ("val",)
) -> dict[str, tuple[str, list[int]]]:
    """Trace-cited names absent from the corpus: ``name -> (def_path, def_pos)``.

    Parameters
    ----------
    kind : str, optional
    splits : tuple[str, ...], optional

    Returns
    -------
    dict[str, tuple[str, list[int]]]
    """
    idx = _index()
    out: dict[str, tuple[str, list[int]]] = {}
    for split in splits:
        path = data_root() / kind / f"{split}.json"
        if not path.exists():
            continue
        for rec in json.loads(path.read_text()):
            for tt in rec.get("traced_tactics") or []:
                annotated = tt.get("annotated_tactic") or []
                for prem in annotated[1] if len(annotated) > 1 else []:
                    n = prem["full_name"]
                    if n not in idx and n not in out:
                        out[n] = (prem["def_path"], list(prem["def_pos"]))
    return out


def parse_print_output(text: str) -> dict[str, dict]:
    """Parse ``lake env lean`` output of ``#print`` commands into ``name -> record``.

    A record starts at a line ``<kind> <name>[.{univs}] : <type>``; the type
    runs to a line ending in ``:=`` (the body follows until the next record
    or message) or to the next record. Message lines are skipped.

    Parameters
    ----------
    text : str

    Returns
    -------
    dict[str, dict]
        ``{"kind", "type", "body"}`` per printed name.
    """
    out: dict[str, dict] = {}
    cur: dict | None = None
    in_body = False
    for line in text.splitlines():
        m = _CHECKED_KIND_RE.match(line)
        if m:
            cur = {"kind": m.group("kind"), "type": "", "body": ""}
            out[m.group("name")] = cur
            in_body = False
            line = m.group("rest")
        elif _LEAN_MSG_RE.match(line) or cur is None:
            cur = None
            continue
        if in_body:
            cur["body"] += ("\n" if cur["body"] else "") + line
        elif line.rstrip().endswith(":="):
            cur["type"] += (" " if cur["type"] else "") + line.rstrip()[:-2].strip()
            in_body = True
        else:
            cur["type"] += (" " if cur["type"] else "") + line.strip()
    return out


def _mathlib_root() -> Path:
    """A built Mathlib for ``lake env lean``: the traced checkout, else
    ``SMOLBENCH_MATHLIB_ROOT``."""
    root = _traced_root()
    if root is not None:
        return root
    env = os.getenv("SMOLBENCH_MATHLIB_ROOT")
    if env and Path(env).is_dir():
        return Path(env)
    raise FileNotFoundError(
        "no built Mathlib: neither the traced checkout under ~/.cache/lean_dojo "
        "nor SMOLBENCH_MATHLIB_ROOT is present"
    )


def check_signatures(
    names: dict[str, tuple[str, list[int]]], batch: int = 40, timeout: int = 900
) -> dict[str, dict]:
    """``#print`` each name against the built Mathlib, importing only its module.

    Parameters
    ----------
    names : dict[str, tuple[str, list[int]]]
        ``name -> (def_path, def_pos)`` as `missing_trace_premises` returns.
    batch : int, optional
        Names per ``lean`` invocation; imports are the union of their modules.
    timeout : int, optional

    Returns
    -------
    dict[str, dict]
        Sidecar records for every name Lean could print.
    """
    import subprocess
    import tempfile

    root = _mathlib_root()
    items = sorted(names.items(), key=lambda kv: (module_of(kv[1][0]) or "", kv[0]))
    out: dict[str, dict] = {}
    for i in range(0, len(items), batch):
        chunk = items[i : i + batch]
        mods = sorted({m for m in (module_of(dp) for _, (dp, _) in chunk) if m})
        src = "\n".join(f"import {m}" for m in mods) + "\n"
        src += "\n".join(f"#print {n}" for n, _ in chunk) + "\n"
        with tempfile.NamedTemporaryFile("w", suffix=".lean", delete=False) as f:
            f.write(src)
            tmp = f.name
        try:
            proc = subprocess.run(
                ["lake", "env", "lean", tmp],
                cwd=root,
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        finally:
            os.unlink(tmp)
        parsed = parse_print_output(proc.stdout + "\n" + proc.stderr)
        for n, (dp, pos) in chunk:
            rec = parsed.get(n)
            if rec is not None:
                out[n] = {**rec, "def_path": dp, "def_pos": pos}
    return out


def write_checked_signatures(
    kind: str = "random", splits: tuple[str, ...] = ("val",)
) -> tuple[Path, int, int]:
    """Build the sidecar for every trace-cited name the corpus lacks.

    Parameters
    ----------
    kind : str, optional
    splits : tuple[str, ...], optional

    Returns
    -------
    tuple[Path, int, int]
        Sidecar path, names wanted, names resolved.
    """
    wanted = missing_trace_premises(kind, splits)
    got = check_signatures(wanted)
    path = checked_signatures_path()
    path.write_text(json.dumps(got, indent=1, ensure_ascii=False))
    _checked.cache_clear()
    return path, len(wanted), len(got)


def _checked_premise(full_name: str) -> Premise | None:
    rec = _checked().get(full_name)
    if rec is None:
        return None
    pos = tuple(rec.get("def_pos") or (0, 0))
    return Premise(
        full_name=full_name,
        code=f"{rec['kind']} {full_name} : {rec['type']}",
        start=pos,  # type: ignore[arg-type]
        end=pos,  # type: ignore[arg-type]
        kind=rec["kind"],
        file_path=rec.get("def_path", ""),
    )


def is_checked(p: Premise) -> bool:
    """Whether ``p`` comes from the checked-signature sidecar, not the corpus."""
    return p.full_name not in _index() and p.full_name in _checked()


_PRIVATE_RE = re.compile(r"^_private\.(?:[^.]+\.)*?0\.")


def lookup(full_name: str) -> Premise | None:
    """Look up a premise by full name.

    Absence renders as a placeholder rather than an error.

    Parameters
    ----------
    full_name : str

    Returns
    -------
    Premise | None
        Corpus record, else a checked-signature record, else None.
    """
    p = _index().get(full_name)
    if p is None and full_name.startswith("_private."):
        # Traces mangle private names (``_private.<module>.0.<name>``); the
        # corpus records them unmangled.
        p = _index().get(_PRIVATE_RE.sub("", full_name))
    return p if p is not None else _checked_premise(full_name)


def signature(p: Premise) -> str:
    """Return source through the first top-level ``:=``.

    Ignore bracketed ``:=`` so attributes do not truncate declarations.

    Parameters
    ----------
    p : Premise

    Returns
    -------
    str
        Rstripped signature.
    """
    s = p.code
    depth = 0
    i = 0
    while i < len(s):
        c = s[i]
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif depth == 0 and c == ":" and i + 1 < len(s) and s[i + 1] == "=":
            return s[:i].rstrip()
        i += 1
    return s.rstrip()


_TOP_LEVEL_RE = re.compile(
    r"^(?:@\[|"
    r"theorem\s|lemma\s|def\s|instance\s|structure\s|inductive\s|"
    r"axiom\s|example\s|class\s|abbrev\s|"
    r"noncomputable\s|private\s|protected\s|partial\s|mutual\s|"
    r"section\s|namespace\s|end\s|end$|"
    r"variable\s|variables\s|"
    r"open\s|import\s|"
    r"syntax\s|macro\s|elab\s|"
    r"deriving\s|attribute\s|set_option\s|"
    r"#)"
)


@lru_cache(maxsize=1)
def _traced_root() -> Path | None:
    """Return the cached repository matching the corpus commit.

    Match the commit to avoid silently slicing another trace; missing source is
    optional, so return ``None`` while other failures surface; only
    `FileNotFoundError` and `KeyError` are caught. Call
    `corpus.reset_caches` after changing ``SMOLBENCH_LEAN_DATA`` mid-process.
    The matching directory is
    ``~/.cache/lean_dojo/leanprover-community-mathlib4-{commit}/mathlib4``.
    """
    try:
        commit = metadata()["from_repo"]["commit"]
    except (FileNotFoundError, KeyError):
        return None
    cache = Path.home() / ".cache" / "lean_dojo"
    candidate = cache / f"leanprover-community-mathlib4-{commit}" / "mathlib4"
    return candidate if candidate.is_dir() else None


def _resolve_source(file_path: str) -> Path | None:
    """Resolve a corpus path in the traced repository.

    Parameters
    ----------
    file_path : str

    Returns
    -------
    Path | None
        Source path, if present.
    """
    root = _traced_root()
    if root is None:
        return None
    candidate = root / file_path
    return candidate if candidate.exists() else None


@lru_cache(maxsize=8192)
def slice_full_decl(
    file_path: str, start_line: int, end_line: int, max_lines: int = 200
) -> str:
    """Slice a declaration and proof from source.

    Stop at the next top-level declaration, ``max_lines``, or EOF.

    Parameters
    ----------
    file_path : str
    start_line : int
        1-indexed start line.
    end_line : int
        1-indexed end line.
    max_lines : int, optional

    Returns
    -------
    str
        Rstripped slice, if source exists.
    """
    src = _resolve_source(file_path)
    if src is None:
        return ""
    lines = src.read_text().splitlines()
    s = max(0, start_line - 1)
    if s >= len(lines):
        return ""
    search_from = max(s + 1, end_line)
    cap = min(s + max_lines, len(lines))
    for i in range(search_from, cap):
        if _TOP_LEVEL_RE.match(lines[i]):
            return "\n".join(lines[s:i]).rstrip()
    return "\n".join(lines[s:cap]).rstrip()


def body_with_proof(p: Premise) -> str:
    """Return a full declaration or its corpus fallback.

    Parameters
    ----------
    p : Premise

    Returns
    -------
    str
        Declaration text.
    """
    if is_checked(p):
        # A generated declaration has no source of its own; its ``def_pos``
        # points at the generating declaration, so never slice there.
        body = _checked()[p.full_name].get("body", "")
        return p.code + (f" :=\n{body}" if body and len(body) <= _CHECKED_BODY_MAX else "")
    sliced = slice_full_decl(p.file_path, p.start[0], p.end[0])
    return sliced or p.code


def has_full_source(p: Premise) -> bool:
    """Whether a traced-source slice is available.

    A corpus ``code`` field can include a proof, so text alone cannot identify
    a slice; `context._render_hint_parts` needs this distinction. Keep
    `body_with_proof` returning usable text for its callers; the second slice
    call is cheap because `slice_full_decl` is cached.

    Parameters
    ----------
    p : Premise

    Returns
    -------
    bool
        Whether traced source was sliced.
    """
    if is_checked(p):
        return False
    return bool(slice_full_decl(p.file_path, p.start[0], p.end[0]))


# ---------------------------------------------------------------------------
# Trace-based derivation index
# ---------------------------------------------------------------------------


def derivation_index_path() -> Path:
    """Sidecar next to the active corpus: ``<data_root>/derivation_index.json``.

    Per corpus because a post-cutoff corpus has its own splits and traces.
    """
    return data_root() / "derivation_index.json"


def build_derivation_index(kind: str = "random") -> dict[str, list[str]]:
    """``full_name -> premises used by its traced proof``, over every split present.

    Reads the raw split JSON (train.json can be hundreds of MB) without going
    through `corpus.load_split`'s cache so the objects can be freed. Premises
    are in first-use order, deduplicated, self-references dropped. A traced
    theorem whose proof named no corpus premise maps to an empty list; that is
    exact for named usage and blind only to what ``simp``/``omega``/typeclass
    search find on their own.

    Parameters
    ----------
    kind : str, optional

    Returns
    -------
    dict[str, list[str]]
    """
    out: dict[str, list[str]] = {}
    for split in ("train", "val", "test"):
        path = data_root() / kind / f"{split}.json"
        if not path.exists():
            continue
        raw = json.loads(path.read_text())
        for rec in raw:
            tts = rec.get("traced_tactics") or []
            if not tts:
                continue
            seen: set[str] = {rec["full_name"]}
            names: list[str] = []
            for tt in tts:
                annotated = tt.get("annotated_tactic") or []
                for p in annotated[1] if len(annotated) > 1 else []:
                    n = p["full_name"]
                    if n not in seen:
                        seen.add(n)
                        names.append(n)
            out[rec["full_name"]] = names
        del raw
    return out


def write_derivation_index() -> Path:
    """Build the index from the active corpus and write the sidecar.

    ``python -m smolbench.deduction.lean.cli build-derivation-index``; run it
    once per corpus so sweeps do not re-read the split JSON on every start.

    Returns
    -------
    Path
        The written sidecar.
    """
    path = derivation_index_path()
    path.write_text(json.dumps(build_derivation_index()))
    _derivation_index.cache_clear()
    return path


@lru_cache(maxsize=1)
def _derivation_index() -> dict[str, list[str]]:
    """Load `derivation_index_path`, or build it in memory when absent.

    Never writes: the active corpus may be a read-only fixture. Cached; call
    `corpus.reset_caches` after repointing ``SMOLBENCH_LEAN_DATA``.
    """
    path = derivation_index_path()
    if path.exists():
        return json.loads(path.read_text())
    return build_derivation_index()


#: A declaration whose proof is one top-level tactic block: the trace covers
#: all of it. ``:= by`` after the signature; a nested ``fun _ => by`` or
#: ``have h := by`` inside a term proof does not match at the first ``:=``.
_TACTIC_PROOF_RE = re.compile(r":=\s*by\b")


def _trace_covers_proof(text: str) -> bool:
    """Whether ``text``'s proof is a single top-level tactic block."""
    i = text.find(":=")
    return i >= 0 and _TACTIC_PROOF_RE.match(text, i) is not None


def dep_source(full_name: str) -> str:
    """Which edge source `referenced_premises` uses.

    ``trace``: the proof is one tactic block and the trace covers it.
    ``trace+text``: a term-mode proof with traced ``by`` sub-blocks; the
    trace is partial, so text references are unioned in. ``text``: untraced.
    ``none``: not in the corpus.

    Parameters
    ----------
    full_name : str

    Returns
    -------
    str
    """
    p = lookup(full_name)
    if full_name in _derivation_index():
        if p is None or _trace_covers_proof(body_with_proof(p) or p.code):
            return "trace"
        return "trace+text"
    return "text" if p is not None else "none"


# ---------------------------------------------------------------------------
# Text fallback: namespace-aware name resolution over the declaration source
# ---------------------------------------------------------------------------


# Lean identifiers: any Unicode letter or subscript may start or continue a
# name (``forall₂_congr``, ``Finset.sum_const_nat``, ``hε``), joined by ``.``
# and ``'``. ``\w`` covers Greek letters and subscripts; ``\d`` is excluded
# from the first character so numerals are not names. A trailing ``.`` (a
# sentence end inside a docstring) is stripped by the caller.
_IDENT_RE = re.compile(r"[^\W\d][\w'.]*")

_NAMESPACE_RE = re.compile(r"^namespace\s+([\w.']+)")
_SECTION_RE = re.compile(r"^section\b")
_END_RE = re.compile(r"^end\b")
_OPEN_RE = re.compile(r"^open\s+(?!scoped\b)(.+)$")


@lru_cache(maxsize=512)
def _source_lines(file_path: str) -> tuple[str, ...] | None:
    """Lines of a corpus source file, or None if it is not on disk."""
    src = _resolve_source(file_path)
    if src is None:
        return None
    return tuple(src.read_text(encoding="utf-8").splitlines())


@lru_cache(maxsize=8192)
def _file_context(file_path: str, line: int) -> tuple[str, tuple[str, ...]]:
    """``(current namespace, opened namespaces)`` in effect at 1-indexed ``line``.

    Tracks ``namespace``/``section``/``end`` nesting and ``open`` commands
    above the line. ``open A in`` and ``open A (x y)`` / ``hiding`` /
    ``renaming`` forms are read as opening ``A``; ``open scoped`` is ignored
    (notation only).

    Parameters
    ----------
    file_path : str
    line : int

    Returns
    -------
    tuple[str, tuple[str, ...]]
    """
    lines = _source_lines(file_path) or ()
    stack: list[str | None] = []  # namespace name, or None for a section
    opens: list[str] = []
    for raw in lines[: max(0, line - 1)]:
        s = raw.strip()
        if m := _NAMESPACE_RE.match(s):
            stack.append(m.group(1))
        elif _SECTION_RE.match(s):
            stack.append(None)
        elif _END_RE.match(s):
            if stack:
                stack.pop()
        elif m := _OPEN_RE.match(s):
            body = re.split(r"\b(?:hiding|renaming|in)\b|\(", m.group(1))[0]
            opens.extend(tok for tok in body.split() if re.fullmatch(r"[\w.']+", tok))
    ns = ".".join(n for n in stack if n)
    return ns, tuple(opens)


def _resolve_name(
    tok: str, ns: str, opens: tuple[str, ...], idx: dict, short_idx: dict
) -> str | None:
    """Resolve an identifier the way Lean would, given the file context.

    Order: exact full name; ``_root_.`` prefix; qualified under the current
    namespace, its ancestors, or an opened namespace (also opened namespaces
    relative to the current one); a bare short name that is globally unique;
    for ``x.foo`` dot notation on a local, the suffix under the same context.
    Returns None when nothing or more than one candidate matches.

    Parameters
    ----------
    tok : str
    ns : str
    opens : tuple[str, ...]
    idx : dict
    short_idx : dict

    Returns
    -------
    str | None
    """
    if tok.startswith("_root_."):
        tok = tok[len("_root_.") :]
    if tok in idx:
        return tok

    parts = ns.split(".") if ns else []
    prefixes = [".".join(parts[:i]) for i in range(len(parts), 0, -1)]
    scopes = set(prefixes) | set(opens) | {f"{p}.{o}" for p in prefixes for o in opens}
    hits = {f"{s}.{tok}" for s in scopes if f"{s}.{tok}" in idx}
    if len(hits) == 1:
        return hits.pop()
    if hits:
        return None  # ambiguous even with context

    if "." not in tok:
        cands = short_idx.get(tok)
        return cands[0] if cands and len(cands) == 1 else None

    # `ext_iff.symm`: a constant followed by projections. Try each dotted
    # prefix, longest first, under the same rules (without recursing into
    # the suffix rule below).
    parts_tok = tok.split(".")
    for cut in range(len(parts_tok) - 1, 0, -1):
        head = ".".join(parts_tok[:cut])
        if head in idx:
            return head
        hits = {f"{s}.{head}" for s in scopes if f"{s}.{head}" in idx}
        if len(hits) == 1:
            return hits.pop()
        if hits:
            return None
        if "." not in head:
            cands = short_idx.get(head)
            if cands and len(cands) == 1:
                return cands[0]

    # `h.trans`-style dot notation on a local: resolve the suffix under the
    # file context only (never by global uniqueness -- too many collisions).
    suffix = parts_tok[-1]
    hits = {f"{s}.{suffix}" for s in scopes if f"{s}.{suffix}" in idx}
    return hits.pop() if len(hits) == 1 else None

#: Excluded Lean tokens; frozen because every identifier checks membership.
_LEAN_NOISE: frozenset[str] = frozenset(
    {
        "theorem",
        "lemma",
        "def",
        "instance",
        "structure",
        "inductive",
        "axiom",
        "example",
        "class",
        "abbrev",
        "fun",
        "let",
        "in",
        "do",
        "if",
        "then",
        "else",
        "match",
        "with",
        "by",
        "have",
        "show",
        "this",
        "true",
        "True",
        "false",
        "False",
        "Type",
        "Prop",
        "Sort",
        "Set",
        "namespace",
        "open",
        "import",
        "section",
        "end",
        "variable",
        "variables",
        "where",
        "macro",
        "syntax",
        "elab",
        "deriving",
        "attribute",
        "set_option",
        "noncomputable",
        "private",
        "protected",
        "partial",
        "mutual",
        "rw",
        "rewrite",
        "simp",
        "exact",
        "apply",
        "intro",
        "intros",
        "rintro",
        "cases",
        "rcases",
        "obtain",
        "use",
        "constructor",
        "refine",
        "refine'",
        "split",
        "and",
        "or",
        "not",
        "iff",
        "exists",
        "forall",
        "all_goals",
        "any_goals",
        "tauto",
        "ring",
        "field_simp",
        "linarith",
        "nlinarith",
        "omega",
        "decide",
        "rfl",
        "trivial",
        "assumption",
        "id",
        "le",
        "lt",
        "ge",
        "gt",
        "eq",
        "ne",
        "of",
        "to",
        "from",
        "h1",
        "h2",
        "h3",
    }
)


@lru_cache(maxsize=1)
def _short_name_index() -> dict[str, list[str]]:
    """Index full names by final segment for bare-name references."""
    out: dict[str, list[str]] = {}
    for full in _index():
        short = full.rsplit(".", 1)[-1]
        out.setdefault(short, []).append(full)
    return out


@lru_cache(maxsize=4096)
def referenced_premises(full_name: str) -> tuple[Premise, ...]:
    """Derivation edges of ``full_name``: the premises its proof uses.

    1. If the benchmark traced ``full_name``'s proof, start from the premises
       its tactics used, in first-use order (exact for named usage). When the
       proof is one top-level tactic block that is the whole answer.
    2. Otherwise, or in addition when the trace covers only ``by`` sub-blocks
       of a term-mode proof, tokenize the declaration source and resolve each
       identifier with the file's ``namespace``/``open`` context
       (`_resolve_name`). This is a reference closure over the whole
       declaration, statement included.

    Tuples keep cached results hashable.

    Parameters
    ----------
    full_name : str

    Returns
    -------
    tuple[Premise, ...]
        Referenced premises; empty if nothing resolves.
    """
    out: list[Premise] = []
    seen: set[str] = {full_name}
    traced = _derivation_index().get(full_name)
    if traced is not None:
        for n in traced:
            p = lookup(n)
            if p is not None and n not in seen:
                seen.add(n)
                out.append(p)

    p = lookup(full_name)
    if p is None:
        return tuple(out)
    text = body_with_proof(p) or p.code  # fallback: corpus signature
    if traced is not None and _trace_covers_proof(text):
        return tuple(out)

    idx = _index()
    short_idx = _short_name_index()
    ns, opens = _file_context(p.file_path, p.start[0])

    for m in _IDENT_RE.finditer(text):
        tok = m.group().rstrip(".")
        if tok in _LEAN_NOISE or len(tok) <= 1:
            continue
        if m.start() > 0 and text[m.start() - 1] == ".":
            # `(...).trans`: a projection on a term, not a constant. Resolve
            # the head under the file context only, never by global uniqueness.
            tok = f"_.{tok}"
        resolved = _resolve_name(tok, ns, opens, idx, short_idx)
        if resolved is not None and resolved not in seen:
            seen.add(resolved)
            out.append(idx[resolved])
    return tuple(out)


def premise_dep_closure(seeds: list[Premise], depth: int) -> list[Premise]:
    """Return the full breadth-first premise closure to ``depth`` hops.

    Excludes seeds; order is hop-major and first-discovered. Uncapped: a cap
    would let two levels render identically and empty their comparison.

    Parameters
    ----------
    seeds : list[Premise]
        Starting premises, excluded from results.
    depth : int

    Returns
    -------
    list[Premise]
        Breadth-first closure.
    """
    if depth <= 0 or not seeds:
        return []
    visited: set[str] = {p.full_name for p in seeds}
    frontier: list[Premise] = list(seeds)
    out: list[Premise] = []
    for _ in range(depth):
        next_frontier: list[Premise] = []
        for p in frontier:
            for ref in referenced_premises(p.full_name):
                if ref.full_name not in visited:
                    visited.add(ref.full_name)
                    next_frontier.append(ref)
                    out.append(ref)
        if not next_frontier:
            break
        frontier = next_frontier
    return out
